sudo: false

language: node_js

node_js:
  - '0.12'

before_install:
  - rvm install 2.2.2 && rvm use 2.2.2

install:
  - bundle install
  - npm install -g gulp
  - npm install

cache:
  directories:
    - node_modules
    - vendor/bundle

script:
 - npm run-script lint
 - npm run-script compile
 - npm run-script buildpages

env:
  global:
  - secure: WJ3lMQmoZKhHGbMz26gq3ZeLqVCKZuFT/7EkG93PHhrS5fkr3HViOxqf2ld+M33L1yUq/L7jv2mmPKF2jfw76uQDACvcwlaoDFmS/UGVU6BLRAFKyovLCRX2EILQN0p1LJ2YyS2Y9oAak97QV6Eck7aSpjmUsxCWT5kgNikWYko=

notifications:
  email:
    on_success: never
    on_failure: never

after_success:
- mkdir -p "deploy/$TRAVIS_TAG"
- cp -a dist/. "deploy/$TRAVIS_TAG"

deploy:
  - provider: script
    skip_cleanup: true
    script: ./publish-pages.sh
    on:
      branch: master
  - provider: s3
    skip_cleanup: true
    access_key_id: AKIAJRPK7RSZINC7HADA
    secret_access_key:
      secure: arp5dQ0jPdM18y20Rpurkf3lBLx70k6ssnIlV+F6Q1j16uWQygwiA17WnXtJlgL8IDEKhxbIDc/lmH2HsMhbQJQdbfpiLmzWNw79HjV5kMkzeOxdGTuFLRfta5iZ4VVNemveRExUjygrbJIIulvhdv0NGLt3BkLUJaWw5zYm2LI=
    bucket: coveo-public-content
    local-dir: deploy
    upload-dir: styleguide
    acl: public_read
    on:
      tags: true
      repo: coveo/styleguide
