sudo: false
language: node_js
git:
  depth: 10
node_js:
  - '0.12'

before_install:
  - rvm install 2.0.0 && rvm use 2.0.0
install:
  - bundle install --jobs=3
  - npm install -g gulp
  - npm install
cache:
  directories:
    - node_modules
    - vendor/bundle

before_script:
 - chmod +x deploy.sh
script:
 - npm run-script deploy
env:
  global:
  - secure: WJ3lMQmoZKhHGbMz26gq3ZeLqVCKZuFT/7EkG93PHhrS5fkr3HViOxqf2ld+M33L1yUq/L7jv2mmPKF2jfw76uQDACvcwlaoDFmS/UGVU6BLRAFKyovLCRX2EILQN0p1LJ2YyS2Y9oAak97QV6Eck7aSpjmUsxCWT5kgNikWYko=

notifications:
  email:
    on_success: never
    on_failure: never

branches:
  only:
    - master

after_success:
- mkdir -p "deploy/$TRAVIS_TAG"
- cp -a dist/. "deploy/$TRAVIS_TAG"

deploy:
  provider: s3
  access_key_id: TODO
  secret_access_key:
    secure: TODO
  bucket: coveo-public-content
  skip_cleanup: true
  local-dir: deploy
  upload-dir: styleguide
  acl: public_read
  on:
    tags: true
    repo: Coveo/styleguide
